/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

//#import "UIKit-Structs.h"
//#import "UIControl.h"
//#import "UIPushButton.h"

@class UIFont, NSString;

@interface UIPushButton : UIControl {
	NSString* _title;	// 60 = 0x3c
	UIFont* _font;	// 64 = 0x40
	CGSize _shadowOffset;	// 68 = 0x44
	CGSize _imageOffset;	// 76 = 0x4c
	CGSize _titlePadding;	// 84 = 0x54
	CFDictionaryRef _info;	// 92 = 0x5c
	struct {
		unsigned selected : 1;
		unsigned drawShadow : 1;
		unsigned disableAutosizeToFit : 1;
		unsigned drawContentsCentered : 1;
		unsigned reverseShadowDirectionWhenHighlighted : 1;
		unsigned stretchBackground : 1;
		unsigned showPressFeedback : 1;
		unsigned disabledDimsImage : 1;
		unsigned alwaysHandleScrollerMouseEvent : 1;
		unsigned drawsImageOnRight : 1;
	} _pushButtonFlags;	// 96 = 0x60
}
+(id)defaultFont;	// 0x3161cfa1
-(id)initWithFrame:(CGRect)frame;	// 0x31513929
-(id)initWithTitle:(id)title;	// 0x31593f2d
-(id)initWithTitle:(id)title autosizesToFit:(BOOL)fit;	// 0x31514345
-(id)initWithImage:(id)image;	// 0x315a167d
-(void)dealloc;	// 0x3152790d
-(unsigned)state;	// 0x31513b81
-(void)setEnabled:(BOOL)enabled;	// 0x31513e41
-(BOOL)isPressed;	// 0x3161cf89
-(void)setSelected:(BOOL)selected;	// 0x315500a9
-(BOOL)isSelected;	// 0x3161cdbd
-(void)setTitle:(id)title;	// 0x315143a9
-(id)title;	// 0x315407b5
-(void)setTitleFont:(id)font;	// 0x31514505
-(id)titleFont;	// 0x31518b61
-(void)setAutosizesToFit:(BOOL)fit;	// 0x31513cf1
-(BOOL)autosizesToFit;	// 0x3161cdd1
-(void)sizeToFit;	// 0x31540639
-(CGPoint)pressFeedbackPosition;	// 0x3161cfc5
-(void)setHighlighted:(BOOL)highlighted;	// 0x31598901
-(void)setTracking:(BOOL)tracking;	// 0x31598b95
-(BOOL)_alwaysHandleScrollerMouseEvent;	// 0x3161cde9
-(void)_setAlwaysHandleScrollerMouseEvent:(BOOL)event;	// 0x3161cdfd
-(void)setTitlePadding:(CGSize)padding;	// 0x3161ce19
-(void)setImageOffset:(CGSize)offset;	// 0x3161ce31
-(void)setDrawsShadow:(BOOL)shadow;	// 0x31514459
-(void)setShadowOffset:(float)offset;	// 0x31594071
-(void)setReverseShadowDirectionWhenHighlighted:(BOOL)highlighted;	// 0x31514475
-(void)setStretchBackground:(BOOL)background;	// 0x31513ca9
-(void)setDrawContentsCentered:(BOOL)centered;	// 0x31514419
-(void)setShowPressFeedback:(BOOL)feedback;	// 0x315be895
-(void)setDrawsImageOnRight:(BOOL)right;	// 0x3161ce49
-(BOOL)drawsShadow;	// 0x3161ce65
-(CGSize)shadowOffset;	// 0x3161ce79
-(CGSize)imageOffset;	// 0x3161ce91
-(BOOL)drawContentsCentered;	// 0x3161cea9
-(void)setImage:(id)image forState:(unsigned)state;	// 0x31564345
-(void)setTitleColor:(id)color forState:(unsigned)state;	// 0x315404d1
-(void)setShadowColor:(id)color forState:(unsigned)state;	// 0x31540591
-(void)setBackground:(id)background forState:(unsigned)state;	// 0x31513d45
-(void)setDisabledDimsImage:(BOOL)image;	// 0x3161cf55
-(id)imageForState:(unsigned)state;	// 0x31513be5
-(id)titleColorForState:(unsigned)state;	// 0x31513f89
-(id)shadowColorForState:(unsigned)state;	// 0x31518cb9
-(id)backgroundForState:(unsigned)state;	// 0x31513c89
-(id)currentImage;	// 0x31513b39
-(id)currentTitleColor;	// 0x31513f21
-(id)currentShadowColor;	// 0x31513fa9
-(id)currentBackground;	// 0x31513c41
-(void)setFrame:(CGRect)frame;	// 0x315139f9
//-(XXStruct_UUz0SD)_backgroundSlices:(CGSize)slices;	// 0x31518d31
-(void)_drawBezelPartInRect:(CGRect)rect;	// 0x3151864d
-(void)drawImageAtPoint:(CGPoint)point fraction:(float)fraction;	// 0x3161cf1d
-(void)drawTitleAtPoint:(CGPoint)point width:(float)width;	// 0x31518b95
-(void)_drawImageAndTextPartInRect:(CGRect)rect;	// 0x31518795
-(void)drawButtonPart:(int)part inRect:(CGRect)rect;	// 0x31518601
-(void)drawRect:(CGRect)rect;	// 0x315185b1
-(void)setNeedsDisplay;	// 0x31513a45
@end

@interface UIPushButton (SyntheticEvents)
-(id)_scriptingInfo;	// 0x31526931
@end

@interface UIPushButton (Original)
-(void)setImage:(id)image;	// 0x3156432d
-(void)setPressedImage:(id)image;	// 0x315be87d
-(id)image;	// 0x3161cf05
-(void)setTitleColor:(id)color;	// 0x3161ceed
-(void)setHighlightedTitleColor:(id)color;	// 0x3161ced5
-(id)titleColor;	// 0x3161cebd
-(void)setShadowColor:(id)color;	// 0x31540579
@end

@interface UIPushButton (Static)
-(void)_removePressFeedback:(id)feedback finished:(id)finished;	// 0x31527989
//-(XXStruct_Xx1ZfA)_currentButtonStateInfo;	// 0x31513eb9
//-(void)_setNeedsDisplay:(XXStruct_Xx1ZfA)display;	// 0x31514009
@end

