/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

//#import "WebKit-Structs.h"
//#import "WebFrame.h"
#import <Foundation/NSObject.h>

typedef struct Position {
	id container;
	int posOffset;
} Position;

typedef struct RangeBoundaryPoint {
	Position _field1;
	id _node;
} RangeBoundaryPoint;

typedef struct VisiblePosition {
	Position _field1;
	int _field2;
} VisiblePosition;

typedef struct Range {
	int _field1;
	id _document;
	RangeBoundaryPoint _field3;
	RangeBoundaryPoint _field4;
} Range;


@class WebFramePrivate;

@interface WebFrame : NSObject {
@private
	WebFramePrivate* _private;	// 4 = 0x4
}
-(id)init;	// 0x332f9a88
-(id)initWithName:(id)name webFrameView:(id)view webView:(id)view3;	// 0x332f9a90
-(void)dealloc;	// 0x332de404
-(void)finalize;	// 0x332f9df4
-(id)name;	// 0x332f9ff8
-(id)frameView;	// 0x332cf470
-(id)webView;	// 0x332d232c
-(id)DOMDocument;	// 0x332d8a88
-(id)frameElement;	// 0x332faec4
-(id)provisionalDataSource;	// 0x332fb65c
-(id)dataSource;	// 0x332d7988
-(void)loadRequest:(id)request;	// 0x33301f80
-(void)_loadData:(id)data MIMEType:(id)type textEncodingName:(id)name baseURL:(id)url unreachableURL:(id)url5;	// 0x332d2668
-(void)loadData:(id)data MIMEType:(id)type textEncodingName:(id)name baseURL:(id)url;	// 0x332f9ac4
-(void)_loadHTMLString:(id)string baseURL:(id)url unreachableURL:(id)url3;	// 0x332d25f4
-(void)loadHTMLString:(id)string baseURL:(id)url;	// 0x332d25c8
-(void)loadAlternateHTMLString:(id)string baseURL:(id)url forUnreachableURL:(id)unreachableURL;	// 0x332f9a98
-(void)loadArchive:(id)archive;	// 0x332fcebc
-(void)stopLoading;	// 0x332faf00
-(void)reload;	// 0x332faf78
-(void)reloadFromOrigin;	// 0x332faf40
-(id)findFrameNamed:(id)named;	// 0x332fdc0c
-(id)parentFrame;	// 0x332fafb0
-(id)childFrames;	// 0x332e3d74
-(id)windowObject;	// 0x332fb014
-(void*)globalContext;	// 0x332fb6a8
//-(OpaqueJSContext*)globalContext;	// 0x332fb6a8
@end

@interface WebFrame (WebKitDebug)
-(id)renderTreeAsExternalRepresentation;	// 0x332f05f0
@end

@interface WebFrame (WebPrivate)
+(id)stringWithData:(id)data textEncodingName:(id)name;	// 0x33303310
-(BOOL)_isDescendantOfFrame:(id)frame;	// 0x332fa454
-(void)_setShouldCreateRenderers:(BOOL)_set;	// 0x332f9a5c
-(CGColorRef)_bodyBackgroundColor;	// 0x332fb050
-(BOOL)_isFrameSet;	// 0x332fa4b0
-(BOOL)_firstLayoutDone;	// 0x332fa4e0
-(int)_loadType;	// 0x332d865c
-(BOOL)needsLayout;	// 0x332dbfe0
-(void)_setLoadsSynchronously:(BOOL)synchronously;	// 0x332d2330
-(BOOL)_loadsSynchronously;	// 0x332f9fc4
-(id)_rectsForRange:(id)range;	// 0x332fb9cc
-(id)_selectionRangeForFirstPoint:(CGPoint)firstPoint secondPoint:(CGPoint)point;	// 0x332ff308
-(id)_selectionRangeForPoint:(CGPoint)point;	// 0x332fe834
-(NSRange)_selectedNSRange;	// 0x332dfc48
-(void)_selectNSRange:(NSRange)range;	// 0x333014f0
-(BOOL)_isDisplayingStandaloneImage;	// 0x332f9ecc
-(unsigned)_pendingFrameUnloadEventCount;	// 0x332fa55c
-(id)fetchApplicationIcon:(id)icon selector:(SEL)selector;	// 0x332f9d30
-(void)_setIsDisconnected:(bool)disconnected;	// 0x332fa590
-(void)_setExcludeFromTextSearch:(bool)textSearch;	// 0x332fa5c4
-(BOOL)_pauseAnimation:(id)animation onNode:(id)node atTime:(double)time;	// 0x332fe68c
-(BOOL)_pauseTransitionOfProperty:(id)property onNode:(id)node atTime:(double)time;	// 0x332fbf38
-(unsigned)_numberOfActiveAnimations;	// 0x332fa5f8
-(BOOL)_has3DContent;	// 0x332f9a80
-(unsigned)formElementsCharacterCount;	// 0x332fa628
-(void)setTimeoutsPaused:(BOOL)paused;	// 0x332fa63c
-(void)selectNSRange:(NSRange)range;	// 0x332f9d0c
-(void)selectWithoutClosingTypingNSRange:(NSRange)range;	// 0x333006b0
-(NSRange)selectedNSRange;	// 0x332fa258
-(void)forceLayoutAdjustingViewSize:(BOOL)size;	// 0x332fa6fc
-(void)_handleKeyEvent:(void*)event;	// 0x332fa76c
//-(void)_handleKeyEvent:(GSEventRef)event;	// 0x332fa76c
-(void)_selectAll;	// 0x332fa78c
-(void)_setSelectionFromNone;	// 0x332fa7a4
-(void)_restoreViewState;	// 0x332f9f84
-(void)_saveViewState;	// 0x332fb43c
-(void)_invalidateOwnerRendererLayoutIfNeeded;	// 0x332fa7b8
-(void)resetTextAutosizingBeforeLayout;	// 0x332e3334
-(void)sendOrientationChangeEvent:(int)event;	// 0x332fa7cc
-(void)setNeedsLayout;	// 0x332db2c8
-(CGSize)renderedSizeOfNode:(id)node constrainedToWidth:(float)width;	// 0x332fb48c
-(void)setUserStyleSheet:(id)sheet;	// 0x332db0b0
-(id)scrollableNodeAtViewportLocation:(CGPoint)viewportLocation;	// 0x332fa83c
-(id)approximateNodeAtViewportLocation:(CGPoint*)viewportLocation;	// 0x332fa864
-(CGRect)renderRectForPoint:(CGPoint)point isReplaced:(BOOL*)replaced fontSize:(float*)size;	// 0x332fa884
-(BOOL)hasCustomViewportArguments;	// 0x332fa8ec
-(void)clearCustomViewportArguments;	// 0x332fa974
-(id)viewportArguments;	// 0x332fa9b4
-(void)_setVisibleSize:(CGSize)size;	// 0x332e3ba8
-(void)_setProhibitsScrolling:(BOOL)scrolling;	// 0x332f9ea8
-(void)revealSelection;	// 0x332fa310
-(void)resetSelection;	// 0x332fa514
-(void)moveSelectionToStartOrEndOfCurrentWord;	// 0x332e0d24
-(BOOL)hasEditableSelection;	// 0x332e0d38
-(int)preferredHeight;	// 0x332db244
-(int)innerLineHeight:(id)height;	// 0x332fa9d8
-(void)updateLayout;	// 0x332db230
-(void)setIsActive:(BOOL)active;	// 0x332db028
-(void)setEmbeddedEditingMode:(BOOL)mode;	// 0x332d9e0c
-(CGRect)caretRect;	// 0x332e0464
-(CGRect)rectForScrollToVisible;	// 0x332e04c0
-(void)createDefaultFieldEditorDocumentStructure;	// 0x332fa9f4
-(void)setCaretColor:(CGColorRef)color;	// 0x332fb21c
-(id)documentView;	// 0x332e048c
-(int)layoutCount;	// 0x332dc000
-(id)selectedDOMRange;	// 0x332e0d54
-(void)setSelectedDOMRange:(id)range affinity:(int)affinity closeTyping:(BOOL)typing;	// 0x332faa08
-(void)expandSelectionToElementContainingCaretSelection;	// 0x332faa54
-(id)elementRangeContainingCaretSelection;	// 0x332ff9cc
-(void)expandSelectionToWordContainingCaretSelection;	// 0x332faa6c
-(void)expandSelectionToStartOfWordContainingCaretSelection;	// 0x332faa84
-(unsigned short)characterInRelationToCaretSelection:(int)caretSelection;	// 0x332e2a90
-(unsigned short)characterBeforeCaretSelection;	// 0x332df9b8
-(unsigned short)characterAfterCaretSelection;	// 0x332e05d8
-(id)wordRangeContainingCaretSelection;	// 0x332df9d0
-(id)wordInRange:(id)range;	// 0x332dfb40
-(int)wordOffsetInRange:(id)range;	// 0x332faa9c
-(BOOL)spaceFollowsWordInRange:(id)range;	// 0x332faacc
-(id)wordsInCurrentParagraph;	// 0x332faafc
-(BOOL)selectionAtDocumentStart;	// 0x332dfb68
-(BOOL)selectionAtSentenceStart;	// 0x332fb1e0
-(BOOL)selectionAtWordStart;	// 0x332fb1a4
-(BOOL)rangeAtSentenceStart:(id)sentenceStart;	// 0x332e0584
-(void)addAutoCorrectMarker:(id)marker;	// 0x332fbc10
-(void)addAutoCorrectMarker:(id)marker word:(id)word correction:(id)correction;	// 0x33302bd8
-(id)rangeByMovingCurrentSelection:(int)selection;	// 0x332fde58
-(id)rangeByExtendingCurrentSelection:(int)selection;	// 0x332fdac0
-(void)selectNSRange:(NSRange)range onElement:(id)element;	// 0x332fab10
-(id)markedTextDOMRange;	// 0x332df44c
-(void)setMarkedText:(id)text selectedRange:(NSRange)range;	// 0x333030c4
-(void)setMarkedText:(id)text forCandidates:(BOOL)candidates;	// 0x33302664
-(void)confirmMarkedText:(id)text;	// 0x332e2ab0
-(void)setText:(id)text asChildOfElement:(id)element breakLines:(BOOL)lines;	// 0x332fbd84
-(void)getPPTStatsWithParseCount:(unsigned*)parseCount withLayoutCount:(unsigned*)layoutCount withForcedLayoutCount:(unsigned*)forcedLayoutCount withParseDuration:(double*)parseDuration withLayoutDuration:(double*)layoutDuration;	// 0x332fab74
-(void)clearPPTStats;	// 0x332fabbc
-(CGRect)caretRectAtNode:(id)node offset:(int)offset affinity:(int)affinity;	// 0x332fa21c
-(id)characterRangeAtPoint:(CGPoint)point;	// 0x332f9ce8
-(NSRange)convertDOMRangeToNSRange:(id)nsrange;	// 0x332fa1f8
-(id)convertNSRangeToDOMRange:(NSRange)domrange;	// 0x332f9cc4
-(CGRect)firstRectForDOMRange:(id)domrange;	// 0x332fa1d4
-(id)fontForSelection:(BOOL*)selection;	// 0x332fabd8
//-(GSFontRef)fontForSelection:(BOOL*)selection;	// 0x332fabd8
-(void)sendScrollEvent;	// 0x332fac7c
-(id)stringByEvaluatingJavaScriptFromString:(id)string forceUserGesture:(BOOL)gesture;	// 0x332f9ca4
-(id)stringForRange:(id)range;	// 0x332f9c88
-(void)_replaceSelectionWithText:(id)text selectReplacement:(BOOL)replacement smartReplace:(BOOL)replace matchStyle:(BOOL)style;	// 0x333028c0
-(void)_replaceSelectionWithWebArchive:(id)webArchive selectReplacement:(BOOL)replacement smartReplace:(BOOL)replace;	// 0x332facd4
-(void)_replaceSelectionWithFragment:(id)fragment selectReplacement:(BOOL)replacement smartReplace:(BOOL)replace matchStyle:(BOOL)style;	// 0x332fcb50
-(void)_replaceSelectionWithText:(id)text selectReplacement:(BOOL)replacement smartReplace:(BOOL)replace;	// 0x332fd7b0
-(void)_replaceSelectionWithMarkupString:(id)markupString baseURLString:(id)string selectReplacement:(BOOL)replacement smartReplace:(BOOL)replace;	// 0x332f9c30
-(id)_documentFragmentForText:(id)text;	// 0x33302df8
-(id)_documentFragmentForWebArchive:(id)webArchive;	// 0x332f9bfc
-(id)_documentFragmentForImageData:(id)imageData withRelativeURLPart:(id)relativeURLPart andMIMEType:(id)type;	// 0x332f9b18
-(BOOL)focusedNodeHasContent;	// 0x332fe0f0
@end

@interface WebFrame (WebInternal)
//+(PassRefPtr<WebCore::Frame>)_createFrameWithPage:(Page*)page frameName:(const String*)name frameView:(id)view ownerElement:(HTMLFrameOwnerElement*)element;	// 0x332ccb9c
+(id)_createFrameWithPage:(id)page frameName:(id)name frameView:(id)view ownerElement:(id)element;	// 0x332ccb9c
//+(void)_createMainFrameWithPage:(Page*)page frameName:(const String*)name frameView:(id)view;	// 0x332ccb20
+(void)_createMainFrameWithPage:(id)page frameName:(id)name frameView:(id)view;	// 0x332ccb20
//+(PassRefPtr<WebCore::Frame>)_createSubframeWithOwnerElement:(HTMLFrameOwnerElement*)ownerElement frameName:(const String*)name frameView:(id)view;	// 0x332fb3d4
+(id)_createSubframeWithOwnerElement:(id)ownerElement frameName:(id)name frameView:(id)view;	// 0x332fb3d4
//+(void)_createMainFrameWithSimpleHTMLDocumentWithPage:(Page*)page frameView:(id)view withStyle:(id)style editable:(BOOL)editable;	// 0x3330229c
+(void)_createMainFrameWithSimpleHTMLDocumentWithPage:(id)page frameView:(id)view withStyle:(id)style editable:(BOOL)editable;	// 0x3330229c
-(void)_attachScriptDebugger;	// 0x332fb518
-(void)_detachScriptDebugger;	// 0x332de0a0
-(id)_initWithWebFrameView:(id)webFrameView webView:(id)view;	// 0x332ccfe4
-(void)_clearCoreFrame;	// 0x332de2b0
-(void)_updateBackgroundAndUpdatesWhileOffscreen;	// 0x332cf1a8
-(void)_setInternalLoadDelegate:(id)delegate;	// 0x332f99e4
-(id)_internalLoadDelegate;	// 0x332f9a08
-(void)_unmarkAllBadGrammar;	// 0x332f9f1c
-(void)_unmarkAllMisspellings;	// 0x332f9a2c
-(BOOL)_hasSelection;	// 0x332dad50
-(void)_clearSelection;	// 0x332dfba4
-(id)_findFrameWithSelection;	// 0x332dacc0
-(void)_clearSelectionInOtherFrames;	// 0x332fa408
-(id)_dataSource;	// 0x332cd93c
-(BOOL)_isCommitting;	// 0x332db9f4
-(void)_setIsCommitting:(BOOL)committing;	// 0x332f9a30
-(void)_addData:(id)data;	// 0x332d8910
-(id)_stringWithDocumentTypeStringAndMarkupString:(id)documentTypeStringAndMarkupString;	// 0x332fc0e0
-(id)_nodesFromList:(id)list;	// 0x332fa050
-(id)_markupStringFromRange:(id)range nodes:(id*)nodes;	// 0x332fc390
-(id)_selectedString;	// 0x333011a8
-(id)_stringForRange:(id)range;	// 0x332e04e8
-(void)_drawRect:(CGRect)rect contentsOnly:(BOOL)only;	// 0x332dbc08
-(id)_computePageRectsWithPrintWidthScaleFactor:(float)printWidthScaleFactor printHeight:(float)height;	// 0x332f9a54
-(BOOL)_getVisibleRect:(CGRect*)rect;	// 0x332fa0d4
-(id)_stringByEvaluatingJavaScriptFromString:(id)string;	// 0x332f9db8
-(id)_stringByEvaluatingJavaScriptFromString:(id)string forceUserGesture:(BOOL)gesture;	// 0x33300d54
-(CGRect)_caretRectAtNode:(id)node offset:(int)offset affinity:(int)affinity;	// 0x332fdfa4
-(CGRect)_firstRectForDOMRange:(id)domrange;	// 0x332fa174
-(void)_scrollDOMRangeToVisible:(id)visible;	// 0x332fb2fc
-(BOOL)_needsLayout;	// 0x332db68c
-(id)_accessibilityTree;	// 0x332fb0d8
-(int)_selectionGranularity;	// 0x332fa2e0
-(NSRange)_convertToNSRange:(id)range;	// 0x332dfdc0
-(id)_convertToDOMRange:(NSRange)range;	// 0x332fb70c
-(id)convertNSRangeToDOMRange:(NSRange)domrange;	// 0x332f9d94
-(id)_convertNSRangeToDOMRange:(NSRange)domrange;	// 0x332fd4ec
-(NSRange)convertDOMRangeToNSRange:(id)nsrange;	// 0x332fa2bc
-(NSRange)_convertDOMRangeToNSRange:(id)nsrange;	// 0x332fa27c
-(id)_markDOMRange;	// 0x332fd654
-(id)_smartDeleteRangeForProposedRange:(id)proposedRange;	// 0x332ffb10
-(id)_documentFragmentWithMarkupString:(id)markupString baseURLString:(id)string;	// 0x33301c60
-(id)_documentFragmentWithNodesAsParagraphs:(id)nodesAsParagraphs;	// 0x332fc62c
-(void)_replaceSelectionWithNode:(id)node selectReplacement:(BOOL)replacement smartReplace:(BOOL)replace matchStyle:(BOOL)style;	// 0x332fc984
-(void)_insertParagraphSeparatorInQuotedContent;	// 0x332fa334
-(id)_visiblePositionForPoint:(CGPoint)point;	// 0x332e084c
//-(VisiblePosition)_visiblePositionForPoint:(CGPoint)point;	// 0x332e084c
-(id)_characterRangeAtPoint:(CGPoint)point;	// 0x332fee20
-(id)_typingStyle;	// 0x332fb800
-(void)_setTypingStyle:(id)style withUndoAction:(int)undoAction;	// 0x332fa3b8
-(BOOL)_canProvideDocumentSource;	// 0x33301a74
-(BOOL)_canSaveAsWebArchive;	// 0x332f9d74
-(void)_receivedData:(id)data textEncodingName:(id)name;	// 0x332d75cc
@end

@interface WebFrame (WebFrameIPhone)
-(id)coreFrame;	// 0x332df758
-(VisiblePosition)visiblePositionForPoint:(CGPoint)point;	// 0x3333d744
-(VisiblePosition)closestWordBoundary:(VisiblePosition)boundary;	// 0x3333f718
-(BOOL)isSingleLine;	// 0x3333d6ec
-(void)setIsSingleLine:(BOOL)line;	// 0x3333d718
-(void)clearSelection;	// 0x3333d830
-(int)selectionState;	// 0x332df71c
-(BOOL)hasSelection;	// 0x332dfc1c
-(CGRect)closestCaretRectForPoint:(CGPoint)point inSelection:(BOOL)selection;	// 0x3333edd8
-(CGRect)closestCaretRectInMarkedTextRangeForPoint:(CGPoint)point;	// 0x33346010
-(void)collapseSelection;	// 0x3333fb64
-(void)extendSelection:(BOOL)selection;	// 0x3333fd98
-(BOOL)pointAtStartOfLine:(CGPoint)line;	// 0x3333e780
-(BOOL)pointAtEndOfLine:(CGPoint)line;	// 0x3333e164
-(id)selectionRectsForCoreRange:(Range*)coreRange;	// 0x3333d9f0
-(id)selectionRectsForRange:(id)range;	// 0x3333d858
-(id)selectionRects;	// 0x3333dd74
-(BOOL)isPoint:(CGPoint)point inRange:(id)range;	// 0x3333e2c4
-(id)wordAtPoint:(CGPoint)point;	// 0x3333de1c
-(void)setRangedSelectionBaseToCurrentSelection;	// 0x3333d88c
-(void)setRangedSelectionBaseToCurrentSelectionStart;	// 0x3333d8ac
-(void)setRangedSelectionBaseToCurrentSelectionEnd;	// 0x3333d8cc
-(void)clearRangedSelectionInitialExtent;	// 0x3333d8ec
-(void)setRangedSelectionInitialExtentToCurrentSelectionStart;	// 0x3333d90c
-(void)setRangedSelectionInitialExtentToCurrentSelectionEnd;	// 0x3333d92c
-(void)setRangedSelectionWithExtentPoint:(CGPoint)extentPoint;	// 0x33345180
-(BOOL)setRangedSelectionExtentPoint:(CGPoint)point baseIsStart:(BOOL)start allowFlipping:(BOOL)flipping;	// 0x33343118
-(BOOL)setSelectionWithBasePoint:(CGPoint)basePoint extentPoint:(CGPoint)point baseIsStart:(BOOL)start allowFlipping:(BOOL)flipping;	// 0x333425b0
-(BOOL)setSelectionWithBasePoint:(CGPoint)basePoint extentPoint:(CGPoint)point baseIsStart:(BOOL)start;	// 0x3333d7cc
-(void)setSelectionWithFirstPoint:(CGPoint)firstPoint secondPoint:(CGPoint)point;	// 0x3333e8e0
-(void)ensureRangedSelectionContainsInitialStartPoint:(CGPoint)point initialEndPoint:(CGPoint)point2;	// 0x3334051c
-(void)aggressivelyExpandSelectionToWordContainingCaretSelection;	// 0x33341834
-(void)expandSelectionToSentence;	// 0x3334118c
-(void)expandSelectionToParagraph;	// 0x333414e0
-(BOOL)selectionIsCaretInDisplayBlockElementAtOffset:(int)offset;	// 0x3333d94c
-(int)selectionBaseWritingDirection:(BOOL*)direction;	// 0x332e067c
-(void)toggleBaseWritingDirection;	// 0x3333d78c
-(void)setBaseWritingDirection:(int)direction;	// 0x332e05f0
-(void)moveSelectionToStart;	// 0x33340edc
-(void)moveSelectionToEnd;	// 0x3333eb28
-(void)moveSelectionToPoint:(CGPoint)point;	// 0x332e06c8
-(void)setSelectionGranularity:(int)granularity;	// 0x3333d978
-(void)smartExtendRangedSelection:(int)selection;	// 0x333492f8
@end

